In [7]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [8]:
car_rental=pd.read_csv("../backend/dataset/car_rental_dataset.csv")

In [9]:
car_rental.head()

,Car_ID,Brand,Model,Fuel_Type,Transmission,Body_Type,Mileage,Engine_CC,Year
0,1,Kia,EV6,Electric,Automatic,SUV,0,0,2024
1,2,Honda,Amaze,Diesel,Automatic,Sedan,20,1199,2019
2,3,Honda,Amaze,Diesel,Manual,Sedan,20,1199,2018
3,4,Honda,Amaze,Petrol,Manual,Sedan,20,1199,2024
4,5,Toyota,Innova,Diesel,Manual,SUV,14,2393,2018

In [10]:
#selecting features

In [11]:
car_rental.columns

Index(['Car_ID', 'Brand', 'Model', 'Fuel_Type', 'Transmission', 'Body_Type',
       'Mileage', 'Engine_CC', 'Year'],
      dtype='str')

In [12]:
car_rental.columns

Index(['Car_ID', 'Brand', 'Model', 'Fuel_Type', 'Transmission', 'Body_Type',
       'Mileage', 'Engine_CC', 'Year'],
      dtype='str')

In [13]:
car_rental.head(10)

,Car_ID,Brand,Model,Fuel_Type,Transmission,Body_Type,Mileage,Engine_CC,Year
0,1,Kia,EV6,Electric,Automatic,SUV,0,0,2024
1,2,Honda,Amaze,Diesel,Automatic,Sedan,20,1199,2019
2,3,Honda,Amaze,Diesel,Manual,Sedan,20,1199,2018
3,4,Honda,Amaze,Petrol,Manual,Sedan,20,1199,2024
4,5,Toyota,Innova,Diesel,Manual,SUV,14,2393,2018
5,6,BMW,3 Series,Diesel,Automatic,Sedan,14,1998,2017
6,7,Hyundai,Verna,Petrol,Manual,Sedan,19,1497,2022
7,8,Maruti,Alto,Petrol,Manual,Hatchback,23,796,2019
8,9,Kia,Seltos,Petrol,Automatic,SUV,16,1497,2022
9,10,Hyundai,Verna,Petrol,Manual,Sedan,20,1497,2023

In [14]:
car_rental["Brand"].unique()

<ArrowStringArray>
['Kia', 'Honda', 'Toyota', 'BMW', 'Hyundai', 'Maruti']
Length: 6, dtype: str

In [15]:
car_rental["Model"].unique()

<ArrowStringArray>
[     'EV6',    'Amaze',   'Innova', '3 Series',    'Verna',     'Alto',
   'Seltos',      'i20',     'City',    'Creta',    'Swift',   'Glanza',
 'Fortuner',       'X1']
Length: 14, dtype: str

In [16]:
car_rental.describe()

            Car_ID       Mileage     Engine_CC          Year
count  10000.00000  10000.000000  10000.000000  10000.000000
mean    5000.50000     16.657000   1477.890100   2019.982100
std     2886.89568      5.993158    660.158157      2.571389
min        1.00000      0.000000      0.000000   2016.000000
25%     2500.75000     14.000000   1197.000000   2018.000000
50%     5000.50000     18.000000   1497.000000   2020.000000
75%     7500.25000     21.000000   1995.000000   2022.000000
max    10000.00000     26.000000   2755.000000   2024.000000

Data Cleaning

In [17]:
car_rental.isna().value_counts()

Car_ID  Brand  Model  Fuel_Type  Transmission  Body_Type  Mileage  Engine_CC  Year
False   False  False  False      False         False      False    False      False    10000
Name: count, dtype: int64

In [18]:
a=car_rental.duplicated()
print(a.sum())

0

In [19]:
null_rows = car_rental[car_rental.isnull().any(axis=1)]
null_rows

Empty DataFrame
Columns: [Car_ID, Brand, Model, Fuel_Type, Transmission, Body_Type, Mileage, Engine_CC, Year]
Index: []

In [20]:
categories=car_rental.select_dtypes(include=['str']).columns
categories

Index(['Brand', 'Model', 'Fuel_Type', 'Transmission', 'Body_Type'], dtype='str')

In [21]:
car_rental[['Brand', 'Model', 'Fuel_Type', 'Transmission', 'Body_Type']].isnull().sum()

Brand           0
Model           0
Fuel_Type       0
Transmission    0
Body_Type       0
dtype: int64

In [22]:
for i in categories:
    car_rental[i]=car_rental[i].fillna("unknown",inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19528\3805569990.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  car_rental[i]=car_rental[i].fillna("unknown",inplace=True)

In [30]:
car_rental.isna().sum()
car_rental["Brand"].unique()

<ArrowStringArray>
['Kia', 'Honda', 'Toyota', 'BMW', 'Hyundai', 'Maruti']
Length: 6, dtype: str

In [24]:
numeric=car_rental.select_dtypes(include=['float'])
numeric

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[10000 rows x 0 columns]

In [25]:
for i in numeric:
    car_rental[i]=car_rental[i].fillna(car_rental[i].median())

In [26]:
car_rental.isna().sum()

Car_ID          0
Brand           0
Model           0
Fuel_Type       0
Transmission    0
Body_Type       0
Mileage         0
Engine_CC       0
Year            0
dtype: int64

In [27]:
car_rental.to_csv(
    "../backend/dataset/car_rental_cleaned.csv",
    index=False
)

In [28]:
car_rental1=pd.read_csv("../backend/dataset/car_rental_cleaned.csv")
car_rental1.isna().sum()

Car_ID          0
Brand           0
Model           0
Fuel_Type       0
Transmission    0
Body_Type       0
Mileage         0
Engine_CC       0
Year            0
dtype: int64